dist: xenial
sudo: false
language: python
python:    
    - "3.7"
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: wayfair
  skip_existing: true  
  password:
    secure: "YplFQ8h64i6GqdD31ZkQl2LteosBGZBNKIlB/5Xj5DQXLF5RknzKeU3hIlnRNRjLs9LXFYdu5hqGJBDoRbEwcoXmbXBeYHFuS+c4lqZSazySRPGWlOzAKG2iDebzf1JW7wR8Mx32lRy9tho4hRQ4e7UkrKQWj5AK+J8n/LmeRnNAcvaH6h8OQvun7+tUVMEQ3Yt8Lq4UREFd2GDMrpISMzbfKiVB+dQT/jpapLtZB0ekwho9mosYknguPe6sIFXW+b5Gl0Leom4vjFCxXYV67EmGt6qpmbyqDE7c84pmwdSeWv87Cgo+yORr1J7p0dPhExZL/pEi8m0w0bbzcdDLdl8vvzF3esknJN8hggUGLIjpeis4SL9bl2qz+79Z7Oem0zx+ccM3WKQdX95TKnSsTQR62defQskZZylX5DJqbt1K0d9felKj9NLWbZsae+4Lv038Fm6BDPDm0o4uZX1pgKVRC6zSwLtMp5ZYYlQfqqNz64yNnN8P8pGqYOCQWe5IpKehJ8vnhYP44mkQkQwvJsPcLiqMpd1sBLoXLEXL1E1Ms3ti4N0ZJUsS4AHUBEm8J6XWErNs6i41Xx8W/6pIWsSOo2Psxq+2BxZOG4yHiMo9Y82Ytok/TVQ29RzqTe6ioy4YZqE7MkXgl31AnY5Oh6eZw59ZZQXcXwXoNXaz3LY="  
  distributions: sdist bdist_wheel