dist: xenial
sudo: false
language: python
python:
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: wayfair
  skip_existing: true
  password:
    secure: CZMpQL7P3YZKwVpj3LdOxWjJ6ONzi6DgYsiOiUO9wkzR7xYe+Xuxaj29QnCksiPT7tzHD/RaMe2+hkheLypIKVa17JhrR0hgIr8EwoOmHYs/vwPXYLDp//42/a6NrIa62DBS7s2LZzWeWdDi/uIgL7bc/iqnSjubDZNpD708YG7llmGWOZMJK5CSKHF+2m0WkzQc1X2jue+tM+mgbindWV4nnouTwyCuz5qR2iTisWQR9Cd1Pb7ECTqb14SbzeH6Vv4kxE+ipxgukVnDKtcHNZDziK2XGHJXDRlfQm74DtQ0ZHW0WQG3KUkq85tUotFeltnMPHMYdBVelHmFXXUayxnyIH5d4oJlGZE2x0FrgU3cGFU+nk1gTAmDOOeSEuj3e0yiS//WupcGApl9KezF1Vj5TXtHZml+GY5lUnEs/VNIfC48lURPRrIi6fzvLLAyJEFybEG6vHPwrURhwrp4uPDLTVAuCr3EZOHZVi7kCaRRmzDdel5y8MxeZdwHMEnAz/VdDSUYldu+ygT2mHv4BU5rcvWA44ftghjv/4zkA1BamLkW9SOM/yYWz93UnPi6RgUsIXZQ90tJqa60YsTXHFZVCj0EYvH+z3OeUbXR60et2cLDyFR1fYVHAYJZ8U2vkfCUaFKyQ5Q7nFAp4OT1WxrCAJLzcbvJ/KqeBc/azbs=
  distributions: sdist bdist_wheel