language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install coveralls
    - pip install Sphinx
    - if (python --version | grep -q 3.5) && (pip freeze | grep pylint | grep -qv 10c668a); then pip uninstall -y pylint; pip install hg+https://bitbucket.org/logilab/pylint@10c668a#egg=pylint; fi
    - if (python --version | grep -q 3.5) && (pip freeze | grep astroid | grep -qv 492bbdc); then pip uninstall -y astroid; pip install hg+https://bitbucket.org/logilab/astroid@492bbdc#egg=astroid; fi

cache:
    directories:
        - $HOME/virtualenv

script:
    - pep8 .
    - pylint aloe aloe_sphinx tests
    - coverage erase
    - coverage run -m nose
    - coverage report
    - ./tools/check_installs
    - make -C docs coverage

after_success:
    - coveralls

sudo: false

deploy:
    provider: pypi
    user: koterpillar
    password:
        secure: "ngmlqV8hod71n7GudGTaW9Re1DXJZvA2XaFOW4FqRbJydkPWdXbZw1FoPiZM8UFQCgWc9D1MuGzs17+cVobe3YWOSW7OG5G7oJBMuLlJ+zDExHb4UusYDi2ADBK2R46ukd1A002sb4ns7X3SC2w1v1oMEp3HIKFGvRVVUf+PfK0="
    server: https://pypi.python.org/pypi
    on:
        tags: true
        all_branches: true
        python: 3.5
        condition: "\"$TRAVIS_TAG\" = \"v$(python setup.py --version)\""
