dist: xenial
sudo: false
language: python
python:
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: wayfair
  skip_existing: true
  password:
    secure: GSyH+BvEfjqVeUghKQbVruf1KyfK+w3iX5A40RUq2Z4K2uUQUGTRs2p4Lz93DRKC3OLehEj07tO6kJQSYSP2UiL9YP2SW6OffqkE/0hv07i4ppIgLxafxl426dfCrQ8AVWPjm43WXtpw705PB+OQBqn+gZ8hThG3dWOQ4Khl7QE547qncGd1LxkzwnzxBv2fF7R4M4Oc4u6nJ8duxUpGAI+/ofaQXx7Z6HsOU29grM83buu1cNiDPsQoPQ3Wh9xjTPMOPEUmCLk4k7CFy+4AzkiKuaOITz0aMt4n/7sbDa/0Lcy2axfhI0vHU6j3GPUDUM2eiCA0KCZ/+069o1nocG5XyadFX1DMyLN2OIWMB36wi8QMqszf1QObn4WF2rQmS7WGOj+jPMbqaPL/08zjvv92nToPpUQDS2j7JLjDHgVSij4mUyAiD+oQ/LdlKi+EkEKdXLl5JRU5XtbveA9YkN6qI6YjexglOdMKw7IXN8PRvf2Iq0VSVc0BdMGGqXXLUoqjumFyvCi+vHM02UZIfQhAUM0T7WMLeHtwcsEA/co7qBweDaCZ32zz3WQ+rH1GN9qmisqu+CJ9BasxbCyX2P68dHT8ZpZQZsfThmo6ouhmd2tVYSeU18oeiMztxxNvmyJjNRAdXgVLz0FS9maNDGGm2gUNlUnMzUyurqavqF0=
  distributions: sdist bdist_wheel
