dist: xenial
sudo: false
language: python
python:
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: wayfair
  skip_existing: true
  password:
    secure: Uo1fS3ELpsCBsvdJKFz9cAPccG+MX5rv2eF21SkACvWEEofiU7sz8N4Aq9zkK/Tef9lJVKcDx+yY2jjQS8qv8Octc9lOsep1ARm7rSax+kYgU0XrX+4xNgQjS8g0PUiX41tv5Q8obl3LxhgaV2zkwCP9uU2adopRnfpr9lxYGfx8KVjReEMs7WbDDMS8kzHMNA4xgUAmaJ7AkO2nPFDKkUYt3CuMR6uIN48cEok5kvHPDFE1AkzCgGX4ZT16PM5APtT3u7ZbwpliAnJWEUvIIMH7xrjyfntbVu0OiVOdhpPJDUI+LUxU9aKXe7OFvWlpnU9zm1ZeH/73mS1+Lqqi+t2WROnUswStYESzNyPYfFaBECnTmGLRSxMWBS8HpkwTTCqxfz5ghuQHqs/KOXAKmI+HcL0ZmDNQfAZsuhPfTOcuXX9PkQc1SJWQXO2YHwTAq7ckF/buGxf7THAU5odOA7Yn0/YTQ85r6fK2CHfnSmTA0BTHQK7aQ8VgaEbSGeMAwxeghAyatfDpneC6eD4Ec8LWMqUKOyPZsBRnhwTIBh94KOoIMMyeeBd0kaMJyonEVp4jjHulKsWKViXHWOtWG4qd6uvAh/b+eITZm/lNc8ZvZsm7tvwXquxvGoNzBCPYsMUQzBFF06FOz2if7rkCfAIWDoEMbWHoyCE5K0ub3Xk=
  distributions: sdist bdist_wheel
